[versions]
android-sdk = "36"
kotlin = "2.2.21"
firebase-bom = "34.7.0"
androidx-media2 = "1.3.0"
coroutines = "1.10.2"
okhttp = "5.3.2"
compose-bom = "2025.12.00"
compose-compiler = "1.5.15"
navigation = "2.9.6"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
media3 = "1.8.0"
ktor = "3.3.3"
arrow = "2.2.0"

[libraries]
android-build-gradle = { module = "com.android.tools.build:gradle", version = "8.13.2"}
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
kotlin-poet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }
java-poet = "com.squareup:javapoet:1.13.0"

kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test",  version.ref = "coroutines" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava",  version.ref = "coroutines" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"

android-material = { module = "com.google.android.material:material", version = "1.13.0" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-mediarouter = { module = "androidx.mediarouter:mediarouter", version = "1.8.1" }
androidx-media2-session = { module = "androidx.media2:media2-session", version.ref = "androidx-media2" }
androidx-media2-widget = { module = "androidx.media2:media2-widget", version.ref = "androidx-media2" }
androidx-media2-player = { module = "androidx.media2:media2-player", version.ref = "androidx-media2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-compose-nav = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

junit = { module = "junit:junit", version = "4.13.2"}
truth = { module = "com.google.truth:truth", version = "1.4.5" }

byteunits = { module = "com.jakewharton.byteunits:byteunits", version = "0.9.1" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
okio = { module = "com.squareup.okio:okio", version = "3.16.4" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.12.1" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons = "androidx.compose.material:material-icons-extended:1.7.8"
androidx-datastore = "androidx.datastore:datastore-preferences:1.2.0"

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3"}
media3-cast = { module = "androidx.media3:media3-cast", version.ref = "media3"}

coil = "io.coil-kt:coil-compose:2.7.0"
coil-svg = "io.coil-kt:coil-svg:2.7.0"

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
arrow-fx = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

markwon = "io.noties.markwon:core:4.6.2"

[bundles]
buildSrc = [
    "android-build-gradle",
    "kotlin-gradle-plugin",
    "kotlin-poet"
]

androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-cardview",
    "androidx-mediarouter",
    "androidx-media2-session",
    "androidx-media2-widget",
    "androidx-media2-player",
    "androidx-constraintlayout",
    "androidx-datastore",
]

android-debug-libs = [
    "leakcanary",
    "androidx-ui-tooling",
]

android-test-libs = [
    "junit",
    "truth",
    "kotlinx-coroutines-test",
]

firebase = [
    "firebase-analytics",
    "firebase-crashlytics"
]

compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-material3",
    "androidx-activity-compose",
    "androidx-material-icons",
    "androidx-ui-tooling-preview"
]

navigation = [
    "androidx-compose-nav"
]

hilt = [
    "hilt-android",
    "hilt-navigation-compose"
]

media3 = [
    "media3-exoplayer",
    "media3-session",
    "media3-ui",
    "media3-common"
]

arrow = [
    "arrow-core",
    "arrow-resilience",
    "arrow-fx"
]

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
version-check = { id = "com.github.ben-manes.versions", version = "0.53.0" }
google-services = { id = "com.google.gms.google-services", version = "4.4.4" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = "com.google.devtools.ksp:2.3.3"
paparazzi = "app.cash.paparazzi:2.0.0-alpha02"
