[versions]
# values used in build scripts
compose-compiler = "1.5.15"
android-sdk = "36"
android-min-sdk = "23"

agp = "8.13.0"
kotlin = "2.2.20"
firebase-bom = "34.3.0"
androidx-media2 = "1.3.0"
flipper = "0.273.0"
coroutines = "1.10.2"
okhttp = "5.1.0"
compose-bom = "2025.09.00"
navigation = "2.9.4"
hilt = "2.57.1"
hiltNavigationCompose = "1.3.0"
media3 = "1.8.0"
ktor = "3.3.0"
arrow = "2.1.2"
androidx-lifecycle = "2.9.4"
coil = "3.3.0"

[libraries]
# buildSrc dependency
java-poet = "com.squareup:javapoet:1.13.0"

kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test",  version.ref = "coroutines" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava",  version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"

android-material = { module = "com.google.android.material:material", version = "1.13.0" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-mediarouter = { module = "androidx.mediarouter:mediarouter", version = "1.8.1" }
androidx-media2-session = { module = "androidx.media2:media2-session", version.ref = "androidx-media2" }
androidx-media2-widget = { module = "androidx.media2:media2-widget", version.ref = "androidx-media2" }
androidx-media2-player = { module = "androidx.media2:media2-player", version.ref = "androidx-media2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-compose-nav = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

multiplatform-compose-navigation = "org.jetbrains.androidx.navigation:navigation-compose:2.9.0"

androidx-runner = { group = "androidx.test", name = "runner", version = "1.7.0" }
androidx-core = { group = "androidx.test", name = "core", version = "1.7.0" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-leakcanary = { module = "com.facebook.flipper:flipper-leakcanary2-plugin", version.ref = "flipper" }
flipper-network-plugin = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }
flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }

facebook-soloader = { module = "com.facebook.soloader:soloader", version = "0.12.1" }

junit = { module = "junit:junit", version = "4.13.2"}
truth = { module = "com.google.truth:truth", version = "1.4.5" }

byteunits = { module = "com.jakewharton.byteunits:byteunits", version = "0.9.1" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }
okio = { module = "com.squareup.okio:okio", version = "3.16.0" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.11.0" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons = "androidx.compose.material:material-icons-extended:1.7.8"
androidx-datastore = "androidx.datastore:datastore-preferences:1.1.7"

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3"}
media3-cast = { module = "androidx.media3:media3-cast", version.ref = "media3"}

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
arrow-fx = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-core-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }

ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

markwon = "io.noties.markwon:core:4.6.2"

[bundles]
androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-cardview",
    "androidx-mediarouter",
    "androidx-media2-session",
    "androidx-media2-widget",
    "androidx-media2-player",
    "androidx-constraintlayout",
    "androidx-datastore",
]

android-debug-libs = [
    "leakcanary",
    "facebook-soloader",
    "flipper",
    "flipper-leakcanary",
    "flipper-network-plugin",
    "androidx-ui-tooling",
]

android-release-libs = [ "flipper-noop" ]

android-test-libs = [
    "junit",
    "truth",
    "kotlinx-coroutines-test",
]

firebase = [
    "firebase-analytics",
    "firebase-crashlytics"
]

compose = [
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-material3",
    "androidx-activity-compose",
    "androidx-material-icons",
    "androidx-ui-tooling-preview"
]

navigation = [
    "androidx-compose-nav"
]

hilt = [
    "hilt-android",
    "hilt-navigation-compose"
]

media3 = [
    "media3-exoplayer",
    "media3-session",
    "media3-ui",
    "media3-common"
]

arrow = [
    "arrow-core",
    "arrow-resilience",
    "arrow-fx"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = "org.jetbrains.compose:1.9.0"
version-check = "com.github.ben-manes.versions:0.52.0"
google-services = "com.google.gms.google-services:4.4.3"
firebase-crashlytics = "com.google.firebase.crashlytics:3.0.6"
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = "com.google.devtools.ksp:2.2.20-2.0.3"
paparazzi = "app.cash.paparazzi:2.0.0-alpha02"
metro = "dev.zacsweers.metro:0.6.6"
